# ABOUTME: Home Assistant MQTT-Integration für Fossibot-Geräte
# WICHTIG: Ersetze 7C2C67AB5F0E durch die MAC-Adresse deines Geräts

mqtt:
  # Batterie & Leistungs-Sensoren
  sensor:
    - name: "Fossibot Batterie"
      unique_id: "fossibot_7c2c67ab5f0e_battery"
      state_topic: "fossibot/7C2C67AB5F0E/state"
      value_template: "{{ value_json.soc }}"
      unit_of_measurement: "%"
      device_class: battery
      icon: mdi:battery

    - name: "Fossibot Eingangsleistung"
      unique_id: "fossibot_7c2c67ab5f0e_input_power"
      state_topic: "fossibot/7C2C67AB5F0E/state"
      value_template: "{{ value_json.inputWatts }}"
      unit_of_measurement: "W"
      device_class: power
      icon: mdi:solar-power

    - name: "Fossibot Ausgangsleistung"
      unique_id: "fossibot_7c2c67ab5f0e_output_power"
      state_topic: "fossibot/7C2C67AB5F0E/state"
      value_template: "{{ value_json.outputWatts }}"
      unit_of_measurement: "W"
      device_class: power
      icon: mdi:power-plug

    - name: "Fossibot Max. Ladestrom"
      unique_id: "fossibot_7c2c67ab5f0e_max_charging_current"
      state_topic: "fossibot/7C2C67AB5F0E/state"
      value_template: "{{ value_json.maxChargingCurrent }}"
      unit_of_measurement: "A"
      device_class: current
      icon: mdi:current-ac

  # Verfügbarkeits-Sensor
  binary_sensor:
    - name: "Fossibot Verfügbar"
      unique_id: "fossibot_7c2c67ab5f0e_availability"
      state_topic: "fossibot/7C2C67AB5F0E/availability"
      payload_on: "online"
      payload_off: "offline"
      device_class: connectivity

  # Ausgangs-Schalter
  switch:
    - name: "Fossibot USB"
      unique_id: "fossibot_7c2c67ab5f0e_usb"
      command_topic: "fossibot/7C2C67AB5F0E/command"
      state_topic: "fossibot/7C2C67AB5F0E/state"
      payload_on: '{"action":"usb_on"}'
      payload_off: '{"action":"usb_off"}'
      value_template: "{{ 'ON' if value_json.usbOutput else 'OFF' }}"
      optimistic: false
      icon: mdi:usb

    - name: "Fossibot AC"
      unique_id: "fossibot_7c2c67ab5f0e_ac"
      command_topic: "fossibot/7C2C67AB5F0E/command"
      state_topic: "fossibot/7C2C67AB5F0E/state"
      payload_on: '{"action":"ac_on"}'
      payload_off: '{"action":"ac_off"}'
      value_template: "{{ 'ON' if value_json.acOutput else 'OFF' }}"
      optimistic: false
      icon: mdi:power-socket-eu

    - name: "Fossibot DC"
      unique_id: "fossibot_7c2c67ab5f0e_dc"
      command_topic: "fossibot/7C2C67AB5F0E/command"
      state_topic: "fossibot/7C2C67AB5F0E/state"
      payload_on: '{"action":"dc_on"}'
      payload_off: '{"action":"dc_off"}'
      value_template: "{{ 'ON' if value_json.dcOutput else 'OFF' }}"
      optimistic: false
      icon: mdi:power-plug

    - name: "Fossibot LED"
      unique_id: "fossibot_7c2c67ab5f0e_led"
      command_topic: "fossibot/7C2C67AB5F0E/command"
      state_topic: "fossibot/7C2C67AB5F0E/state"
      payload_on: '{"action":"led_on"}'
      payload_off: '{"action":"led_off"}'
      value_template: "{{ 'ON' if value_json.ledOutput else 'OFF' }}"
      optimistic: false
      icon: mdi:lightbulb

  # Einstellungs-Eingaben
  number:
    - name: "Fossibot Max. Ladestrom"
      unique_id: "fossibot_7c2c67ab5f0e_set_charging_current"
      command_topic: "fossibot/7C2C67AB5F0E/command"
      command_template: '{"action":"set_charging_current","amperes":{{ value | int }}}'
      state_topic: "fossibot/7C2C67AB5F0E/state"
      value_template: "{{ value_json.maxChargingCurrent }}"
      min: 1
      max: 20
      step: 1
      unit_of_measurement: "A"
      icon: mdi:current-ac

    - name: "Fossibot Entladegrenze"
      unique_id: "fossibot_7c2c67ab5f0e_discharge_limit"
      command_topic: "fossibot/7C2C67AB5F0E/command"
      command_template: '{"action":"set_discharge_limit","percentage":{{ value | float }}}'
      state_topic: "fossibot/7C2C67AB5F0E/state"
      value_template: "{{ value_json.dischargeLowerLimit }}"
      min: 0
      max: 100
      step: 1
      unit_of_measurement: "%"
      icon: mdi:battery-arrow-down

    - name: "Fossibot AC-Ladegrenze"
      unique_id: "fossibot_7c2c67ab5f0e_ac_charging_limit"
      command_topic: "fossibot/7C2C67AB5F0E/command"
      command_template: '{"action":"set_ac_charging_limit","percentage":{{ value | float }}}'
      state_topic: "fossibot/7C2C67AB5F0E/state"
      value_template: "{{ value_json.acChargingUpperLimit }}"
      min: 0
      max: 100
      step: 1
      unit_of_measurement: "%"
      icon: mdi:battery-arrow-up

# Beispiel-Automation
automation:
  - alias: "Fossibot - AC einschalten bei hoher Batterie"
    trigger:
      - platform: numeric_state
        entity_id: sensor.fossibot_battery
        above: 90
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.fossibot_ac_output
